# Generated by Django 5.2.1 on 2025-05-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltask",
            name="reminders",
            field=models.JSONField(
                blank=True, default=list, help_text="Напоминания о задаче", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="time_intervals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Временные интервалы выполнения задачи",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="dependencies",
            field=models.ManyToManyField(
                blank=True,
                help_text="Задачи, от которых зависит текущая",
                related_name="task_dependencies",
                to="tasks.task",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="reminders",
            field=models.JSONField(
                blank=True, default=list, help_text="Напоминания о задаче", null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_intervals",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Временные интервалы выполнения задачи",
                null=True,
            ),
        ),
    ]
