# Generated by Django 5.2.1 on 2025-06-20 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_fileattachment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltask",
            name="progress_dependencies",
            field=models.IntegerField(
                default=0,
                help_text="Прогресс выполнения в процентах (0-100%)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Прогресс выполнения зависимостей",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="progress_dependencies",
            field=models.IntegerField(
                default=0,
                help_text="Прогресс выполнения в процентах (0-100%)",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Прогресс выполнения зависимостей",
            ),
        ),
    ]
