# Generated by Django 5.2.1 on 2025-05-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_alter_historicaltask_reminders_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltask",
            name="reminders",
            field=models.JSONField(
                blank=True, default="", help_text="Напоминания о задаче", null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicaltask",
            name="time_intervals",
            field=models.JSONField(
                blank=True,
                default="",
                help_text="Временные интервалы выполнения задачи",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="reminders",
            field=models.JSONField(
                blank=True, default="", help_text="Напоминания о задаче", null=True
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="time_intervals",
            field=models.JSONField(
                blank=True,
                default="",
                help_text="Временные интервалы выполнения задачи",
                null=True,
            ),
        ),
    ]
